import "./globals.css";
import NavBar from "../components/NavBar";
import SideBar from "../components/SideBar";
import NavigationWrapper from "../components/NavigationWrapper";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavigationWrapper>
        <NavBar />
        <SideBar />
        {children}
        </NavigationWrapper>
      </body>
    </html>
  );
}
